branch-defaults:
  main:
    environment: ai-file-manager-dev
    group_suffix: null
global:
  application_name: ai_file_manager
  branch: null
  default_ec2_keyname: aws-file-manager-eb
  default_platform: Python 3.8 running on 64bit Amazon Linux 2
  default_region: ca-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
