# Generated by Django 5.1 on 2024-08-12 00:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_directory_file_path', models.TextField()),
                ('current_file_path', models.TextField()),
                ('entity_type', models.TextField()),
                ('primary_category', models.TextField()),
                ('sub_categories', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
