# Generated by Django 5.1 on 2024-08-12 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_file_file_created_at_date_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='current_file_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
