# Generated by Django 5.1 on 2024-08-15 01:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_file_current_file_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_directory_name', models.TextField()),
                ('user_directory_path', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='file',
            old_name='current_file_name',
            new_name='file_name',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='current_file_path',
            new_name='file_path',
        ),
        migrations.RemoveField(
            model_name='file',
            name='user_directory_file_path',
        ),
        migrations.AddField(
            model_name='file',
            name='directory_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.directory'),
        ),
    ]
