# Generated by Django 5.1 on 2024-08-15 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_directory_rename_current_file_name_file_file_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='file',
            name='screenshot_image',
            field=models.ImageField(blank=True, null=True, upload_to='screenshots/'),
        ),
        migrations.AlterField(
            model_name='file',
            name='entity_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='primary_category',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='sub_categories',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
