# Generated by Django 5.1 on 2024-08-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_useroauth_userprofile_directory_user_profile_obj'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_view_preference',
            field=models.TextField(default='entity'),
        ),
    ]
