# Generated by Django 5.1 on 2024-08-17 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_userprofile_user_view_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='files_under_process',
            field=models.BooleanField(default=False),
        ),
    ]
