# Generated by Django 5.1 on 2024-08-27 17:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_emailsubscriber_remove_file_directory_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOAuth',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auth_zero_id', models.TextField()),
                ('name', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('email_verified', models.BooleanField()),
                ('profile_picture_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
