# Generated by Django 5.1 on 2024-08-30 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_userprofile_files_under_process_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_view_preference',
            field=models.TextField(default='entity'),
        ),
    ]
